
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author doquangminh
 */
public class Frame20_AddBook extends javax.swing.JFrame {

    /**
     * Creates new form Frame6_ProfileManager
     */
    public Frame20_AddBook() {
        initComponents();
         DefaultTableCellRenderer headerCellRenderer = new DefaultTableCellRenderer();
         headerCellRenderer.setBackground(Color.WHITE);
         headerCellRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
         headerCellRenderer.setFont(new Font("Avenir Next", Font.BOLD, 16));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddBook = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        textFieldTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldAuthor = new javax.swing.JTextField();
        textFieldAudio = new javax.swing.JTextField();
        textFieldCategory = new javax.swing.JTextField();
        btnAddCover = new javax.swing.JButton();
        btnDeleteCover = new javax.swing.JButton();
        textFieldImage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldPdf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        btnImportPDF = new javax.swing.JButton();
        btnDeletePDF = new javax.swing.JButton();
        btnDeleteAudio = new javax.swing.JButton();
        btnImportAudio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 113, 164));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Book ");

        jLabel2.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        jLabel2.setText("Book ID");

        btnAddBook.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        btnAddBook.setText("Add this book");
        btnAddBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddBookMouseExited(evt);
            }
        });
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        textFieldTitle.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        textFieldTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        textFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTitleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        jLabel3.setText("Category");

        jLabel4.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        jLabel4.setText("Author");

        jLabel5.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        jLabel5.setText("Title");

        textFieldAuthor.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        textFieldAuthor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        textFieldAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAuthorActionPerformed(evt);
            }
        });

        textFieldAudio.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        textFieldAudio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        textFieldAudio.setEnabled(false);
        textFieldAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAudioActionPerformed(evt);
            }
        });

        textFieldCategory.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        textFieldCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        textFieldCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCategoryActionPerformed(evt);
            }
        });

        btnAddCover.setFont(new java.awt.Font("Avenir Next", 1, 16)); // NOI18N
        btnAddCover.setText("Add Cover");
        btnAddCover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddCoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddCoverMouseExited(evt);
            }
        });
        btnAddCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoverActionPerformed(evt);
            }
        });

        btnDeleteCover.setFont(new java.awt.Font("Avenir Next", 1, 16)); // NOI18N
        btnDeleteCover.setText("Delete");
        btnDeleteCover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteCoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteCoverMouseExited(evt);
            }
        });
        btnDeleteCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCoverActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        jLabel6.setText("Pdf file");

        textFieldPdf.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        textFieldPdf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        textFieldPdf.setEnabled(false);
        textFieldPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPdfActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        jLabel7.setText("Audio");

        textFieldId.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        textFieldId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        textFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdActionPerformed(evt);
            }
        });

        btnImportPDF.setFont(new java.awt.Font("Avenir Next", 1, 16)); // NOI18N
        btnImportPDF.setText("Import");
        btnImportPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImportPDFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImportPDFMouseExited(evt);
            }
        });
        btnImportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportPDFActionPerformed(evt);
            }
        });

        btnDeletePDF.setFont(new java.awt.Font("Avenir Next", 1, 16)); // NOI18N
        btnDeletePDF.setText("Delete");
        btnDeletePDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletePDFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletePDFMouseExited(evt);
            }
        });
        btnDeletePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePDFActionPerformed(evt);
            }
        });

        btnDeleteAudio.setFont(new java.awt.Font("Avenir Next", 1, 16)); // NOI18N
        btnDeleteAudio.setText("Delete");
        btnDeleteAudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteAudioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteAudioMouseExited(evt);
            }
        });
        btnDeleteAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAudioActionPerformed(evt);
            }
        });

        btnImportAudio.setFont(new java.awt.Font("Avenir Next", 1, 16)); // NOI18N
        btnImportAudio.setText("Import");
        btnImportAudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImportAudioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImportAudioMouseExited(evt);
            }
        });
        btnImportAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportAudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                        .addComponent(textFieldCategory, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                        .addGap(41, 41, 41))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAddBook)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textFieldPdf)
                                    .addComponent(textFieldAudio)
                                    .addComponent(textFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnImportPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnDeletePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAddCover, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnDeleteCover, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnImportAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnDeleteAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteCover)
                            .addComponent(btnAddCover))
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(98, 98, 98))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(textFieldPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnImportPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDeletePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(textFieldAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDeleteAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnImportAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
        String id = textFieldId.getText();
        
        boolean notDuplicate = ManageData.getManageData().checkingNotDuplicateBook(id);
        
        if (notDuplicate){
            if (id.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter valid ID!");
            }
            else{
                ManageData.getManageData().allBook.put(id, new Book());
                ManageData.getManageData().allBook.get(id).setAuthor(textFieldAuthor.getText());
                ManageData.getManageData().allBook.get(id).setCategory(textFieldCategory.getText());
                ManageData.getManageData().allBook.get(id).setIdBook(id);
                ManageData.getManageData().allBook.get(id).setTitle(textFieldTitle.getText());
                ManageData.getManageData().allBook.get(id).setAvailable("Yes");
        
                String path = ManageData.getManageData().getTemporaryAvatar();
                ManageData.getManageData().allBook.get(id).setLink(path);
                
                
                //Set link pdf file
                String path3 = textFieldPdf.getText();
                File file = new File(path3);
                String newPath = "src/main/java/pdfFiles/" + file.getName();
                File file2 = new File(newPath);
                ManageData.getManageData().allBook.get(id).setLinkPdf(newPath);
                try{
                    ManageData.getManageData().copyFileUsingChannel(file, file2);
                }
                catch (Exception e){
                    System.out.println("");
                }
                
                //Set link audio file
                String path2 = textFieldAudio.getText();
                File file3 = new File(path2);
                String newPath2 = "src/main/java/audioFiles/" + file3.getName();
                File file4 = new File(newPath2);
                ManageData.getManageData().allBook.get(id).setLinkAudio(newPath2);
                try{
                    ManageData.getManageData().copyFileUsingChannel(file3, file4);
                }
                catch (Exception e){
                    System.out.println("");
                }
                
                
                
                ManageData.getManageData().saveAllBook();
                JOptionPane.showMessageDialog(null, "Add book successfully!\nPress \"Cancel\" to return");
            }
 
        }
        else{
            JOptionPane.showMessageDialog(null, "There already existed an ID book.\nPlease enter another ID!");
        }

    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnAddBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBookMouseExited
        // TODO add your handling code here:
        btnAddBook.setBackground(new Color(255, 255, 255));
        btnAddBook.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddBookMouseExited

    private void btnAddBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBookMouseEntered
        // TODO add your handling code here:
        btnAddBook.setBackground(new Color(20, 142, 255));
        btnAddBook.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAddBookMouseEntered

    private void textFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTitleActionPerformed

    private void textFieldAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAuthorActionPerformed

    private void textFieldAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAudioActionPerformed

    private void textFieldCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCategoryActionPerformed

    private void btnAddCoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCoverMouseEntered
        // TODO add your handling code here:
        btnAddCover.setBackground(new Color(20, 142, 255));
        btnAddCover.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAddCoverMouseEntered

    private void btnAddCoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCoverMouseExited
        // TODO add your handling code here:
        btnAddCover.setBackground(new Color(255, 255, 255));
        btnAddCover.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddCoverMouseExited

    private void btnAddCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoverActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if (f!=null){
            String path = f.getAbsolutePath();       
            
            //Create image
            Image im = Toolkit.getDefaultToolkit().createImage(path);
            im = im.getScaledInstance(textFieldImage.getWidth(), textFieldImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(im);
            
            textFieldImage.setText("");
            textFieldImage.setIcon(ii);
            
            
            File file = new File(path);
            String newPath = "src/main/java/imageBook/" + file.getName();
            File file2 = new File(newPath);
            String userUsing = ManageData.getManageData().getWho_is_using_this_program();
            ManageData.getManageData().setTemporaryAvatar(newPath);
            
            try{
                ManageData.getManageData().copyFileUsingChannel(file, file2);
            }
            catch (Exception e){
                System.out.println("");
            }
        }
    }//GEN-LAST:event_btnAddCoverActionPerformed

    private void btnDeleteCoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCoverMouseEntered
        // TODO add your handling code here:
        btnDeleteCover.setBackground(new Color(255, 59, 48));
        btnDeleteCover.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnDeleteCoverMouseEntered

    private void btnDeleteCoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCoverMouseExited
        // TODO add your handling code here:
        btnDeleteCover.setBackground(new Color(255, 255, 255));
        btnDeleteCover.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnDeleteCoverMouseExited

    private void btnDeleteCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCoverActionPerformed
        // TODO add your handling code here:

        ManageData.getManageData().setTemporaryAvatar(null);
        
            String linkAvatar = null;
            Image im = Toolkit.getDefaultToolkit().createImage(linkAvatar);
            im = im.getScaledInstance(textFieldImage.getWidth(), textFieldImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(im);
            textFieldImage.setText("");
            textFieldImage.setIcon(ii);
    }//GEN-LAST:event_btnDeleteCoverActionPerformed

    private void textFieldPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPdfActionPerformed

    private void textFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Frame16_Book_Manager frame16 = new Frame16_Book_Manager();
        frame16.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        btnCancel.setBackground(new Color(255, 255, 255));
        btnCancel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        // TODO add your handling code here:
        btnCancel.setBackground(new Color(20, 142, 255));
        btnCancel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnImportPDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportPDFMouseEntered
        // TODO add your handling code here:
        btnImportPDF.setBackground(new Color(20, 142, 255));
        btnImportPDF.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnImportPDFMouseEntered

    private void btnImportPDFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportPDFMouseExited
        // TODO add your handling code here:
        btnImportPDF.setBackground(new Color(255, 255, 255));
        btnImportPDF.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnImportPDFMouseExited

    private void btnImportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportPDFActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if (f!=null){
            String path = f.getAbsolutePath();
            textFieldPdf.setText(path);
        }
    }//GEN-LAST:event_btnImportPDFActionPerformed

    private void btnDeletePDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePDFMouseEntered
        // TODO add your handling code here:
        btnDeletePDF.setBackground(new Color(255, 59, 48));
        btnDeletePDF.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnDeletePDFMouseEntered

    private void btnDeletePDFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePDFMouseExited
        // TODO add your handling code here:
        btnDeletePDF.setBackground(new Color(255, 255, 255));
        btnDeletePDF.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnDeletePDFMouseExited

    private void btnDeletePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePDFActionPerformed
        // TODO add your handling code here:
        textFieldPdf.setText("");
    }//GEN-LAST:event_btnDeletePDFActionPerformed

    private void btnDeleteAudioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAudioMouseEntered
        // TODO add your handling code here:
        btnDeleteAudio.setBackground(new Color(255, 59, 48));
        btnDeleteAudio.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnDeleteAudioMouseEntered

    private void btnDeleteAudioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAudioMouseExited
        // TODO add your handling code here:
        btnDeleteAudio.setBackground(new Color(255, 255, 255));
        btnDeleteAudio.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnDeleteAudioMouseExited

    private void btnDeleteAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAudioActionPerformed
        // TODO add your handling code here:
        textFieldAudio.setText("");
    }//GEN-LAST:event_btnDeleteAudioActionPerformed

    private void btnImportAudioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportAudioMouseEntered
        // TODO add your handling code here:
        btnImportAudio.setBackground(new Color(20, 142, 255));
        btnImportAudio.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnImportAudioMouseEntered

    private void btnImportAudioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportAudioMouseExited
        // TODO add your handling code here:
        btnImportAudio.setBackground(new Color(255, 255, 255));
        btnImportAudio.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnImportAudioMouseExited

    private void btnImportAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportAudioActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if (f!=null){
            String path = f.getAbsolutePath();
            textFieldAudio.setText(path);
        }
    }//GEN-LAST:event_btnImportAudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame6_ProfileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame6_ProfileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame6_ProfileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame6_ProfileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame20_AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAddCover;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteAudio;
    private javax.swing.JButton btnDeleteCover;
    private javax.swing.JButton btnDeletePDF;
    private javax.swing.JButton btnImportAudio;
    private javax.swing.JButton btnImportPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textFieldAudio;
    private javax.swing.JTextField textFieldAuthor;
    private javax.swing.JTextField textFieldCategory;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JLabel textFieldImage;
    private javax.swing.JTextField textFieldPdf;
    private javax.swing.JTextField textFieldTitle;
    // End of variables declaration//GEN-END:variables
}
